# Generated by Django 5.1.2 on 2024-10-19 19:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcard',
            old_name='card_holder_name',
            new_name='holder_name',
        ),
        migrations.RenameField(
            model_name='creditcard',
            old_name='card_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='debitcard',
            old_name='card_holder_name',
            new_name='holder_name',
        ),
        migrations.RenameField(
            model_name='debitcard',
            old_name='card_number',
            new_name='number',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debitcard',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
