# Generated by Django 5.1.2 on 2024-10-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_rename_card_holder_name_creditcard_holder_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='issue_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='debitcard',
            name='issue_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
