# Generated by Django 5.1.2 on 2024-10-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_alter_creditcard_issue_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitcard',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
