# Generated by Django 5.1.2 on 2024-10-22 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_alter_debitcard_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=1500, max_digits=10),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
    ]
